export const FSM_STATES = {
  IDLE: "IDLE",
  WAITING_TEACHER: "WAITING_TEACHER",
  WAITING_CATEGORY: "WAITING_CATEGORY",
  WAITING_DESCRIPTION: "WAITING_DESCRIPTION",
  WAITING_CONFIRMATION: "WAITING_CONFIRMATION",
};
