export const FSM_STATES = {
  IDLE: "IDLE",

  WAITING_QUESTION_INPUT: "WAITING_QUESTION_INPUT",
  WAITING_SIMILAR_DECISION: "WAITING_SIMILAR_DECISION",
  WAITING_TEACHER: "WAITING_TEACHER",
  WAITING_CATEGORY: "WAITING_CATEGORY",
  WAITING_DESCRIPTION: "WAITING_DESCRIPTION",
  WAITING_CONFIRMATION: "WAITING_CONFIRMATION",

  WAITING_CLARIFICATION_REPLY: "WAITING_CLARIFICATION_REPLY",

  WAITING_SLOT_SELECTION: "WAITING_SLOT_SELECTION",

  WAITING_DELETE_CONFIRM: "WAITING_DELETE_CONFIRM",

  WAITING_CLARIFY_TYPES: "WAITING_CLARIFY_TYPES",
  WAITING_CLARIFY_COMMENT: "WAITING_CLARIFY_COMMENT",

  WAITING_TEACHER_REPLY: "WAITING_TEACHER_REPLY",
  WAITING_REJECT_REASON: "WAITING_REJECT_REASON",
  WAITING_CONSULTATION_SLOTS: "WAITING_CONSULTATION_SLOTS",
};
