export const CLARIFICATION_TYPES = {
  REPO_LINK: "REPO_LINK",
  GROUP_NUMBER: "GROUP_NUMBER",
  ERROR_SCREENSHOT: "ERROR_SCREENSHOT",
  LESSON_TOPIC: "LESSON_TOPIC",
};

export const CLARIFICATION_SELECTABLE_TYPES = [
  CLARIFICATION_TYPES.REPO_LINK,
  CLARIFICATION_TYPES.GROUP_NUMBER,
  CLARIFICATION_TYPES.ERROR_SCREENSHOT,
  CLARIFICATION_TYPES.LESSON_TOPIC,
];

export const CLARIFICATION_LABELS = {
  [CLARIFICATION_TYPES.REPO_LINK]: "Ссылка на репозиторий",
  [CLARIFICATION_TYPES.GROUP_NUMBER]: "Номер группы",
  [CLARIFICATION_TYPES.ERROR_SCREENSHOT]: "Скриншот ошибки",
  [CLARIFICATION_TYPES.LESSON_TOPIC]: "Тема занятия",
};
